# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createaccountdesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(50, 50, 250, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.mainLabel.setFont(font)
        self.mainLabel.setObjectName("mainLabel")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(135, 120, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(140, 230, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.usernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(75, 150, 200, 30))
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(75, 260, 200, 30))
        self.passwordInput.setObjectName("passwordInput")
        self.usernameErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameErrorLabel.setGeometry(QtCore.QRect(75, 190, 250, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.usernameErrorLabel.setFont(font)
        self.usernameErrorLabel.setText("")
        self.usernameErrorLabel.setObjectName("usernameErrorLabel")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(100, 340, 150, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.createButton.setFont(font)
        self.createButton.setObjectName("createButton")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.returnButton.setObjectName("returnButton")
        self.passwordErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordErrorLabel.setGeometry(QtCore.QRect(75, 300, 250, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passwordErrorLabel.setFont(font)
        self.passwordErrorLabel.setText("")
        self.passwordErrorLabel.setObjectName("passwordErrorLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainLabel.setText(_translate("MainWindow", "Create an Account"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.createButton.setText(_translate("MainWindow", "Create Account"))
        self.returnButton.setText(_translate("MainWindow", "Back to Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
